spring:
#  mvc:
#    favicon:
#      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://ls-ea5c0d0629a8cc8a80428da3902f9351759ae363.cemxsedh0w8x.ap-northeast-2.rds.amazonaws.com"
    port: 3306
    username: "admin"
    password: "]or`$>P5Q+,M=gpPpU.QgI,{an``e7c3"
  redis:
    host: 15.165.86.75
    port: 6379
    password: penekhunCTFJserver!@!@
    #todo: 대회 직전엔 DB정보들 환경변수나 실행 인자값으로 뺍시다
    #todo: 코드 분석툴에 무조건 걸릴듯 - hun

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

jwt:
  header: Authorization
  secret: VkZ2ODNoZGlqY25TUHBjamM0ODI5Mzg1N3ZBU0MzRGNNWjljODQ5MkFsQzBzOVhYWmM4c1BFMk4yS2tra0RTYVlJU0YyMWNzUQ
  token-validity-in-seconds: 1800 # 30?
  refresh-token-validity-in-seconds: 10800 # 3??